// backend/src/services/metaCapi.js
// META DESACTIVADO el 2026-07-06 por migración a Shopify.
// Para reactivar: descomentar todo el bloque de código de abajo y restaurar el module.exports al final.

// // Meta Conversions API — server-side events with browser Pixel deduplication via event_id
// //
// // Deduplication contract:
// //   Purchase:         eventID = "purchase_<orderId>"      — matches metaPixel.js trackPurchase()
// //   InitiateCheckout: eventID = order.metaEventId (UUID   — generated by CheckoutSheet before Pixel fires)
// //                     Fallback: "initcheckout_<orderId>"  — if frontend didn't send metaEventId
//
// const crypto = require('crypto');
//
// // Meta tracking desactivado el 2026-07-06 por migración a Shopify. Poner en true para reactivar.
// const META_TRACKING_ENABLED = process.env.META_TRACKING_ENABLED === 'true';
//
// const PIXEL_ID        = process.env.META_PIXEL_ID;
// const ACCESS_TOKEN    = process.env.META_CAPI_TOKEN;
// const TEST_EVENT_CODE = process.env.META_TEST_EVENT_CODE || null;
// const GRAPH_VERSION   = 'v21.0';
//
// function sha256(value) {
//     if (!value) return undefined;
//     return crypto.createHash('sha256').update(String(value).toLowerCase().trim()).digest('hex');
// }
//
// function normalizeArgPhone(phone) {
//     if (!phone) return null;
//     let digits = String(phone).replace(/\D/g, '');
//     if (!digits) return null;
//     if (digits.startsWith('54') && digits.length >= 11) return '+' + digits;
//     if (digits.startsWith('0')) digits = '54' + digits.slice(1);
//     else if (digits.length === 10) digits = '54' + digits;
//     else if (digits.length === 8) digits = '5411' + digits;
//     return '+' + digits;
// }
//
// function buildUserData(order, ctx = {}) {
//     const nameParts  = (order.customerName || '').trim().split(/\s+/);
//     const firstName  = nameParts[0] || '';
//     const lastName   = nameParts.slice(1).join(' ') || '';
//     const e164Phone  = normalizeArgPhone(order.customerPhone);
//     const ud = {};
//     if (order.customerEmail) ud.em = [sha256(order.customerEmail)];
//     if (e164Phone)           ud.ph = [sha256(e164Phone)];
//     if (firstName)           ud.fn = [sha256(firstName)];
//     if (lastName)            ud.ln = [sha256(lastName)];
//     if (order.fbp)           ud.fbp = order.fbp;
//     if (order.fbc)           ud.fbc = order.fbc;
//     const ip = order.clientIp || ctx.ip;
//     const ua = order.clientUserAgent || ctx.userAgent;
//     if (ip) ud.client_ip_address  = ip;
//     if (ua) ud.client_user_agent  = ua;
//     return ud;
// }
//
// async function sendCapiEvent({ eventName, eventId, userData, customData }) {
//     if (!META_TRACKING_ENABLED) return;
//     if (!PIXEL_ID || !ACCESS_TOKEN) {
//         console.warn('⚠️ Meta CAPI: META_PIXEL_ID o META_CAPI_TOKEN no configurados — saltando evento.');
//         return;
//     }
//     const payload = {
//         data: [{
//             event_name:    eventName,
//             event_time:    Math.floor(Date.now() / 1000),
//             event_id:      eventId,
//             action_source: 'website',
//             user_data:     userData,
//             custom_data:   customData,
//         }],
//         ...(TEST_EVENT_CODE ? { test_event_code: TEST_EVENT_CODE } : {}),
//     };
//     try {
//         const res  = await fetch(
//             `https://graph.facebook.com/${GRAPH_VERSION}/${PIXEL_ID}/events?access_token=${ACCESS_TOKEN}`,
//             { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }
//         );
//         const json = await res.json();
//         if (!res.ok) {
//             console.warn(`⚠️ Meta CAPI [${eventName}] error:`, JSON.stringify(json));
//         } else {
//             console.log(`✅ Meta CAPI ${eventName} enviado — eventID: ${eventId}`);
//         }
//     } catch (err) {
//         console.warn(`⚠️ Meta CAPI [${eventName}] fetch error:`, err?.message || err);
//     }
// }
//
// async function sendPurchaseEvent(order, ctx = {}) {
//     if (!order?._id) {
//         console.warn('⚠️ Meta CAPI sendPurchaseEvent: orden sin _id.');
//         return;
//     }
//     const orderId = order._id.toString();
//     return sendCapiEvent({
//         eventName:  'Purchase',
//         eventId:    `purchase_${orderId}`,
//         userData:   buildUserData(order, ctx),
//         customData: {
//             currency:     'ARS',
//             value:        order.totalAmount,
//             num_items:    order.totalItems,
//             contents:     (order.items || []).map(it => ({ id: String(it.productId || ''), quantity: it.quantity })),
//             content_type: 'product',
//             order_id:     orderId,
//         },
//     });
// }
//
// async function sendInitiateCheckoutEvent(order, ctx = {}) {
//     if (!order?._id) return;
//     const orderId = order._id.toString();
//     const eventId = order.metaEventId || `initcheckout_${orderId}`;
//     return sendCapiEvent({
//         eventName:  'InitiateCheckout',
//         eventId,
//         userData:   buildUserData(order, ctx),
//         customData: {
//             currency:     'ARS',
//             value:        order.totalAmount,
//             num_items:    order.totalItems,
//             contents:     (order.items || []).map(it => ({ id: String(it.productId || ''), quantity: it.quantity })),
//             content_type: 'product',
//         },
//     });
// }
//
// async function sendEarlyInitiateCheckoutEvent({ metaEventId, fbp, fbc, value, currency, clientIp, clientUserAgent }) {
//     const eventId = metaEventId || `initcheckout_early_${Date.now()}`;
//     const userData = {};
//     if (fbp)             userData.fbp                = fbp;
//     if (fbc)             userData.fbc                = fbc;
//     if (clientIp)        userData.client_ip_address  = clientIp;
//     if (clientUserAgent) userData.client_user_agent  = clientUserAgent;
//     return sendCapiEvent({
//         eventName:  'InitiateCheckout',
//         eventId,
//         userData,
//         customData: {
//             currency:     currency || 'ARS',
//             value:        Number(value) || 0,
//             content_type: 'product',
//         },
//     });
// }
//
// module.exports = { sendPurchaseEvent, sendInitiateCheckoutEvent, sendEarlyInitiateCheckoutEvent };

module.exports = {};
