// backend/src/services/metaCapi.js
// Meta Conversions API — server-side events with browser Pixel deduplication via event_id
//
// Deduplication contract:
//   Purchase:         eventID = "purchase_<orderId>"      — matches metaPixel.js trackPurchase()
//   InitiateCheckout: eventID = order.metaEventId (UUID   — generated by CheckoutSheet before Pixel fires)
//                     Fallback: "initcheckout_<orderId>"  — if frontend didn't send metaEventId

const crypto = require('crypto');

// Meta tracking desactivado el 2026-07-06 por migración a Shopify. Poner en true para reactivar.
const META_TRACKING_ENABLED = process.env.META_TRACKING_ENABLED === 'true';

const PIXEL_ID        = process.env.META_PIXEL_ID;
const ACCESS_TOKEN    = process.env.META_CAPI_TOKEN;
const TEST_EVENT_CODE = process.env.META_TEST_EVENT_CODE || null;
const GRAPH_VERSION   = 'v21.0';

// SHA-256 required by Meta for PII fields (email, phone, name)
function sha256(value) {
    if (!value) return undefined;
    return crypto.createHash('sha256').update(String(value).toLowerCase().trim()).digest('hex');
}

// Normalize an Argentine phone number to E.164 format before hashing.
// Meta requires E.164 (e.g. +5491112345678) for phone matching quality.
function normalizeArgPhone(phone) {
    if (!phone) return null;
    let digits = String(phone).replace(/\D/g, '');
    if (!digits) return null;
    // Already has country code 54 and is long enough
    if (digits.startsWith('54') && digits.length >= 11) return '+' + digits;
    // Local with leading 0 (011..., 0351...)
    if (digits.startsWith('0')) digits = '54' + digits.slice(1);
    // 10-digit mobile without leading 0 (1112345678)
    else if (digits.length === 10) digits = '54' + digits;
    // 8-digit landline — assume Buenos Aires area code 11
    else if (digits.length === 8) digits = '5411' + digits;
    return '+' + digits;
}

// Build user_data object from order + optional request context
// NOT hashed: fbp, fbc, client_ip_address, client_user_agent
// HASHED:     em, ph, fn, ln
function buildUserData(order, ctx = {}) {
    const nameParts  = (order.customerName || '').trim().split(/\s+/);
    const firstName  = nameParts[0] || '';
    const lastName   = nameParts.slice(1).join(' ') || '';
    const e164Phone  = normalizeArgPhone(order.customerPhone);

    const ud = {};

    if (order.customerEmail) ud.em = [sha256(order.customerEmail)];
    if (e164Phone)           ud.ph = [sha256(e164Phone)];
    if (firstName)           ud.fn = [sha256(firstName)];
    if (lastName)            ud.ln = [sha256(lastName)];

    // fbp / fbc: plain text, saved on order at creation time
    if (order.fbp)           ud.fbp = order.fbp;
    if (order.fbc)           ud.fbc = order.fbc;

    // IP and UA: prefer stored fields (from original request), fall back to ctx
    const ip = order.clientIp || ctx.ip;
    const ua = order.clientUserAgent || ctx.userAgent;
    if (ip) ud.client_ip_address  = ip;
    if (ua) ud.client_user_agent  = ua;

    return ud;
}

// Low-level function: POST a single event to the Graph API
async function sendCapiEvent({ eventName, eventId, userData, customData }) {
    if (!META_TRACKING_ENABLED) return;
    if (!PIXEL_ID || !ACCESS_TOKEN) {
        console.warn('⚠️ Meta CAPI: META_PIXEL_ID o META_CAPI_TOKEN no configurados — saltando evento.');
        return;
    }

    const payload = {
        data: [{
            event_name:    eventName,
            event_time:    Math.floor(Date.now() / 1000),
            event_id:      eventId,
            action_source: 'website',
            user_data:     userData,
            custom_data:   customData,
        }],
        // Only included in TEST environment — remove META_TEST_EVENT_CODE in production
        ...(TEST_EVENT_CODE ? { test_event_code: TEST_EVENT_CODE } : {}),
    };

    try {
        const res  = await fetch(
            `https://graph.facebook.com/${GRAPH_VERSION}/${PIXEL_ID}/events?access_token=${ACCESS_TOKEN}`,
            { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }
        );
        const json = await res.json();
        if (!res.ok) {
            console.warn(`⚠️ Meta CAPI [${eventName}] error:`, JSON.stringify(json));
        } else {
            console.log(`✅ Meta CAPI ${eventName} enviado — eventID: ${eventId}`);
        }
    } catch (err) {
        console.warn(`⚠️ Meta CAPI [${eventName}] fetch error:`, err?.message || err);
    }
}

/**
 * Purchase — fires when payment is fully confirmed.
 *
 * eventID = "purchase_<orderId>" must match metaPixel.js trackPurchase() exactly.
 * Called from:
 *   - mercadopagoWebhook.controller.js  (status === 'approved')
 *   - orders.routes.js card-payment     (result.status === 'approved')
 *   - orders.controller.js              (transfer: verifyPaymentProof, COD: admin marks paid)
 *
 * @param {Object} order  Mongoose order document
 * @param {Object} [ctx]  { ip, userAgent } — fallback if not stored on order
 */
async function sendPurchaseEvent(order, ctx = {}) {
    if (!order?._id) {
        console.warn('⚠️ Meta CAPI sendPurchaseEvent: orden sin _id.');
        return;
    }
    const orderId = order._id.toString();
    return sendCapiEvent({
        eventName:  'Purchase',
        eventId:    `purchase_${orderId}`,
        userData:   buildUserData(order, ctx),
        customData: {
            currency:     'ARS',
            value:        order.totalAmount,
            num_items:    order.totalItems,
            contents:     (order.items || []).map(it => ({ id: String(it.productId || ''), quantity: it.quantity })),
            content_type: 'product',
            order_id:     orderId,
        },
    });
}

/**
 * InitiateCheckout — fires when an order is created (user committed to the purchase).
 *
 * eventID = order.metaEventId (UUID generated by CheckoutSheet.jsx before the browser
 * Pixel fires, stored on the order). This allows Meta to deduplicate the browser event
 * and this server-side event as a single InitiateCheckout.
 * Falls back to "initcheckout_<orderId>" if metaEventId was not captured.
 *
 * Called from orders.controller.js createOrder for all payment methods.
 *
 * @param {Object} order  Mongoose order document
 * @param {Object} [ctx]  { ip, userAgent } — unused if saved on order
 */
async function sendInitiateCheckoutEvent(order, ctx = {}) {
    if (!order?._id) return;
    const orderId = order._id.toString();
    const eventId = order.metaEventId || `initcheckout_${orderId}`;
    return sendCapiEvent({
        eventName:  'InitiateCheckout',
        eventId,
        userData:   buildUserData(order, ctx),
        customData: {
            currency:     'ARS',
            value:        order.totalAmount,
            num_items:    order.totalItems,
            contents:     (order.items || []).map(it => ({ id: String(it.productId || ''), quantity: it.quantity })),
            content_type: 'product',
        },
    });
}

/**
 * Early InitiateCheckout — fires immediately when the browser Pixel fires,
 * before the user creates an order. Used by POST /api/meta/initiate-checkout.
 *
 * No order object available yet — only cookies + request context.
 * The metaEventId must match the UUID passed to the browser track() call so
 * Meta can deduplicate both as a single InitiateCheckout event.
 *
 * @param {Object} params
 * @param {string}  params.metaEventId     UUID from the browser Pixel call
 * @param {string}  [params.fbp]           _fbp cookie value (plain text)
 * @param {string}  [params.fbc]           _fbc cookie value (plain text)
 * @param {number}  params.value           Cart total (validated > 0 by caller)
 * @param {string}  params.currency        Always 'ARS' (validated by caller)
 * @param {string}  [params.clientIp]      req.ip
 * @param {string}  [params.clientUserAgent] req.headers['user-agent']
 */
async function sendEarlyInitiateCheckoutEvent({ metaEventId, fbp, fbc, value, currency, clientIp, clientUserAgent }) {
    const eventId = metaEventId || `initcheckout_early_${Date.now()}`;
    const userData = {};
    if (fbp)             userData.fbp                = fbp;
    if (fbc)             userData.fbc                = fbc;
    if (clientIp)        userData.client_ip_address  = clientIp;
    if (clientUserAgent) userData.client_user_agent  = clientUserAgent;

    return sendCapiEvent({
        eventName:  'InitiateCheckout',
        eventId,
        userData,
        customData: {
            currency:     currency || 'ARS',
            value:        Number(value) || 0,
            content_type: 'product',
        },
    });
}

module.exports = { sendPurchaseEvent, sendInitiateCheckoutEvent, sendEarlyInitiateCheckoutEvent };
